import os
from typing import Dict, Any

from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain.chat_models import init_chat_model
from langchain.messages import ToolMessage
from langchain.tools import tool
from langchain_pinecone import PineconeVectorStore
from langchain_openai import OpenAIEmbeddings
load_dotenv()
#initialize embeddings and vector store
embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

vectorStore = PineconeVectorStore(index_name="langchain-doc-index", embedding=embeddings)

# Initialize chat model
model = init_chat_model(model="gpt-4o-mini",model_provider="openai")

@tool(response_format="content_and_artifact")
def retrieve_context(query: str):
    """RETRIEVE_CONTEXT: Retrieve relevant documents from the vector store based on the query."""
    retrieved_docs = vectorStore.as_retriever().invoke(query,k= 5)
    serialized = "\n\n".join((f"Source: {doc.metadata['source']}\nContent: {doc.page_content}" for doc in retrieved_docs))
    return serialized, retrieved_docs


def run_llm(query:str):
    """Run the RAG  pipeline to answer a query using retrieved documents.
    
    Args:
        query (str): The user's query to be answered.
    
    returns:
        Dictionary containing :
            - answer: The final answer generated by the LLM.
            - sources: List of sources (documents) that were used to generate the answer.
    """

    system_prompt = (
        "You are a helpful AI assistant that answers questions about LangChain documentation. "
        "You have access to a tool that retrieves relevant documentation. "
        "Use the tool to find relevant information before answering questions. "
        "Always cite the sources you use in your answers. "
        "If you cannot find the answer in the retrieved documentation, say so."
    )

    agent = create_agent(model,tools = [retrieve_context],system_prompt=system_prompt)
    
    messages = [{"role":"user","content":query}]
    response = agent.invoke({"messages": messages})
    # print("LLM Response:", response)
    answer = response["messages"][-1].content

    #extract context documents from ToolMessage artifacts
    context_docs = []
    for message in response["messages"]:
        if isinstance(message, ToolMessage) and hasattr(message, "artifact"):
         #artifact should contain the list of document objects
            if isinstance(message.artifact ,list):
                context_docs.extend(message.artifact)
    
    return {"answer": answer, "context": context_docs}


if __name__ == "__main__":
    result = run_llm(query="what are deep agents?")
    print(result)
